version: '2'
volumes:
  logs:
    driver: local
services:
  slim:
    image: oivoodoo/php-fpm-rdkafka-alpine
    working_dir: /var/www
    command: 'php -S 0.0.0.0:8088 -t public'
    environment:
      docker: 'true'
    ports:
      - '8088:8088'
    volumes:
      - '.:/var/www'
      - 'logs:/var/www/logs'
